name: Node.js backend to production

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd backend && npm ci
    - run: cd backend && npm run build --if-present
    - name: Upload to remote server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        source: backend/*
        target: /var/backend/temp
        
    - name: Install dependencies and start the server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          rm -rf /var/www/backend
          mkdir /var/www/backend
          mv /var/backend/temp/backend/* /var/www/backend
          echo "ENV_VAR=${{ secrets.ENV_VAR }}" > /var/www/backend/.env
          cd /var/www/backend
          npm install --production
